### ISSUE TITLE
YML does not publish

### ISSUE THREAD

**Issue by DanShoubridge** [MicrosoftDocs/pipelines-dotnet-core#12]
Apologies if I've got this completely wrong (I suspect I have as this is my first go), but have spent quite some time trying to get pipelines to build and release using this YML for an ASP.Net Core WebApi project.

This line: 
`- script: dotnet publish --configuration $(buildConfiguration) --output $(buildConfiguration)`
will run, but with a warning:
`##[warning]Directory '/home/vsts/work/1/a' is empty. Nothing will be added to build artifact 'drop'.`
and won't publish a zipped file to be picked up for release, then in the release pipeline you get the following error: 
`Error: No package found with specified pattern: D:\a\r1\a\**\*.zip`

instead, we needed to use DotNetCoreCLI for it to work:
```
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: False
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
```
All examples I've seen don't mention this at all, I only found it after looking at what the visual designer produced.
